/**
 * JKM Dry Clean - Comprehensive Official Services & Rate Card Catalog
 * Directly sourced from JKM Dry Clean Official Rate Card
 * Shop: JKM DRY CLEAN, Noida Sec 68, Garhi Chaukhandi, UP 201301
 * Phone: +91 85868 25438 | Email: jkmdryclean68@gmail.com
 */

const DEFAULT_SERVICES = [
  // ==========================================
  // 1. GARMENTS — DRY CLEAN & STEAM IRON
  // ==========================================
  {
    name: 'Shirt / T-Shirt (Dry Clean)',
    category: 'Garments',
    price: 109,
    unit: 'Pc',
    description: 'Eco-safe closed-loop hydrocarbon dry cleaning with gentle collar and cuff stain removal.',
    turnaroundTime: '24-48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Shirt / T-Shirt (Steam Iron)',
    category: 'Garments',
    price: 39,
    unit: 'Pc',
    description: 'High-pressure vacuum steam press for wrinkle-free crisp finish and sanitized fabric.',
    turnaroundTime: '24 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Trouser / Pant (Dry Clean)',
    category: 'Garments',
    price: 109,
    unit: 'Pc',
    description: 'Specialized dry cleaning preserving fabric dye, drape, and pocket lining cleanliness.',
    turnaroundTime: '24-48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Trouser / Pant (Steam Iron)',
    category: 'Garments',
    price: 39,
    unit: 'Pc',
    description: 'Precision Italian crease alignment and steam pressing without shine marks.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Pyjama / Salwar / Churidar (Dry Clean)',
    category: 'Garments',
    price: 99,
    unit: 'Pc',
    description: 'Gentle dry cleaning for ethnic bottoms, preserving drawstring and seam elasticity.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Pyjama / Salwar / Churidar (Steam Iron)',
    category: 'Garments',
    price: 39,
    unit: 'Pc',
    description: 'Smooth steam press for ethnic pyjama, salwar, and churidar bottoms.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Shorts (Dry Clean)',
    category: 'Garments',
    price: 99,
    unit: 'Pc',
    description: 'Sanitized fabric dry clean for casual, denim, and athletic shorts.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Shorts (Steam Iron)',
    category: 'Garments',
    price: 39,
    unit: 'Pc',
    description: 'Crisp steam press for cotton, linen, and denim shorts.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Jeans (Dry Clean)',
    category: 'Garments',
    price: 109,
    unit: 'Pc',
    description: 'Color-lock dry cleaning that maintains raw and stretch denim fiber texture without fading.',
    turnaroundTime: '24-48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1542272604-780c96856592?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Jeans (Steam Iron)',
    category: 'Garments',
    price: 49,
    unit: 'Pc',
    description: 'Heavy steam pressing with seam stretching and deep crease setting.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Kurta / Kurti - Plain (Dry Clean)',
    category: 'Garments',
    price: 99,
    unit: 'Pc',
    description: 'Delicate fabric wash with eco-solvent care for cotton and linen plain kurtas.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Kurta / Kurti - Embroidered (Dry Clean)',
    category: 'Garments',
    price: 149,
    unit: 'Pc',
    description: 'Expert dry cleaning protecting zari, beadwork, mirror craft, and delicate embroidery.',
    turnaroundTime: '24-48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Kurta / Kurti (Steam Iron)',
    category: 'Garments',
    price: 49,
    unit: 'Pc',
    description: 'Gentle vertical steam pressing safeguarding pleats, buttons, and neckline motifs.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Sherwani - Plain / Standard (Dry Clean)',
    category: 'Garments',
    price: 499,
    unit: 'Pc',
    description: 'Formal sherwani cleaning with form-fitting hanger finish and lint removal.',
    turnaroundTime: '48-72 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1597983073493-88cd35cf93b0?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Sherwani - Heavy / Designer (Dry Clean)',
    category: 'Garments',
    price: 999,
    unit: 'Pc',
    description: 'Hand-spotted bridal & festive sherwani care preserving heavy zardozi, gems, and velvet.',
    turnaroundTime: '48-72 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1597983073493-88cd35cf93b0?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Sherwani - Plain (Steam Iron)',
    category: 'Garments',
    price: 199,
    unit: 'Pc',
    description: 'Precision steam pressing for plain and raw silk sherwanis.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1597983073493-88cd35cf93b0?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Sherwani - Heavy (Steam Iron)',
    category: 'Garments',
    price: 299,
    unit: 'Pc',
    description: 'Master hand-steaming for heavy embroidered and wedding sherwanis.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1597983073493-88cd35cf93b0?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Coat / Blazer (Dry Clean)',
    category: 'Garments',
    price: 249,
    unit: 'Pc',
    description: 'Executive blazer & suit coat dry cleaning with shoulder shaping and inner lining freshening.',
    turnaroundTime: '24-48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Coat / Blazer (Steam Iron)',
    category: 'Garments',
    price: 149,
    unit: 'Pc',
    description: 'Contoured dummy steam finish preserving lapel roll and shoulder pads.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Overcoat (Dry Clean)',
    category: 'Garments',
    price: 299,
    unit: 'Pc',
    description: 'Heavy wool and trench overcoat cleaning with deep lint extraction and moth-proofing.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Overcoat (Steam Iron)',
    category: 'Garments',
    price: 199,
    unit: 'Pc',
    description: 'Deep penetrating steam press for heavy winter overcoats and trench coats.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Jacket - Standard Non-Leather (Dry Clean)',
    category: 'Garments',
    price: 249,
    unit: 'Pc',
    description: 'Thorough cleaning for bomber, denim, and fleece jackets with zipper lubrication.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Jacket - Heavy / Padded Non-Leather (Dry Clean)',
    category: 'Garments',
    price: 499,
    unit: 'Pc',
    description: 'Specialized down-feather and quilted winter jacket cleaning with loft restoration.',
    turnaroundTime: '48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1544923246-77307dd654cb?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Jacket - Standard (Steam Iron)',
    category: 'Garments',
    price: 99,
    unit: 'Pc',
    description: 'Quick steam touch-up for lightweight jackets and blousons.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Jacket - Heavy (Steam Iron)',
    category: 'Garments',
    price: 199,
    unit: 'Pc',
    description: 'Intense steam puffing for padded and heavy winter jackets.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1544923246-77307dd654cb?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Blouse / Dupatta - Plain (Dry Clean)',
    category: 'Garments',
    price: 99,
    unit: 'Pc',
    description: 'Gentle fabric cleaning for chiffon, georgette, and cotton blouses or dupattas.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Blouse / Dupatta - Plain (Steam Iron)',
    category: 'Garments',
    price: 49,
    unit: 'Pc',
    description: 'Fine silk-safe steam press preventing edge curls and crease damage.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Lehenga - Plain (Dry Clean)',
    category: 'Garments',
    price: 499,
    unit: 'Set',
    description: 'Voluminous skirt flare restoration with non-toxic hydrocarbon eco cleaning.',
    turnaroundTime: '48-72 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Lehenga - Embroidered (Dry Clean)',
    category: 'Garments',
    price: 799,
    unit: 'Set',
    description: 'Heavy sequin, stone, and thread-work protected dry cleaning with custom netting wash.',
    turnaroundTime: '48-72 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Lehenga Bridal (Dry Clean)',
    category: 'Garments',
    price: 1299,
    unit: 'Set',
    description: 'Couture grade bridal lehenga restoration with individual gem inspection and museum-box fold.',
    turnaroundTime: '72 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Saree - Plain (Dry Clean)',
    category: 'Garments',
    price: 199,
    unit: 'Pc',
    description: 'Complete 6-yard saree cleaning with soft conditioning and pristine roll finish.',
    turnaroundTime: '24-48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Saree - Embroidered / Heavy (Dry Clean)',
    category: 'Garments',
    price: 399,
    unit: 'Pc',
    description: 'Special care for designer sarees with intricate borders, pallu work, and zari threading.',
    turnaroundTime: '48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Saree - Plain (Steam Iron)',
    category: 'Garments',
    price: 99,
    unit: 'Pc',
    description: 'Wide flat-bed roller steam press creating flawless crisp folds without scorch risk.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Saree - Embroidered / Heavy (Steam Iron)',
    category: 'Garments',
    price: 199,
    unit: 'Pc',
    description: 'Manual hand-steaming for heavy borders and embroidered pallus.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Silk Saree - Plain (Dry Clean)',
    category: 'Garments',
    price: 249,
    unit: 'Pc',
    description: 'Pure Banarasi, Kanjivaram, and Tussar silk specialized dry cleaning preserving natural sheen.',
    turnaroundTime: '48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Silk Saree - Heavy / Zari (Dry Clean)',
    category: 'Garments',
    price: 499,
    unit: 'Pc',
    description: 'Heritage silk dry cleaning with metallic thread preservation and archival acid-free wrapping.',
    turnaroundTime: '48-72 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Silk Saree - Plain (Steam Iron)',
    category: 'Garments',
    price: 99,
    unit: 'Pc',
    description: 'Low-heat pressurized steam finishing tailored specifically for pure silk weaves.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Silk Saree - Heavy (Steam Iron)',
    category: 'Garments',
    price: 199,
    unit: 'Pc',
    description: 'Specialized velvet-cushioned steam press for heavy zari borders.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Shawl - Plain (Dry Clean)',
    category: 'Garments',
    price: 99,
    unit: 'Pc',
    description: 'Gentle dry clean for Pashmina, wool, and cashmere shawls without shrinking.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Shawl - Plain (Steam Iron)',
    category: 'Garments',
    price: 49,
    unit: 'Pc',
    description: 'Even temperature steam pressing to relax wool and cashmere fibers.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Skirt - Plain (Dry Clean)',
    category: 'Garments',
    price: 149,
    unit: 'Pc',
    description: 'Eco-cleaning for casual and formal skirts maintaining silhouette and color depth.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Skirt - Long / Pleated (Dry Clean)',
    category: 'Garments',
    price: 249,
    unit: 'Pc',
    description: 'Precision pleat preservation dry clean for maxi and pleated skirts.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Skirt - Plain (Steam Iron)',
    category: 'Garments',
    price: 79,
    unit: 'Pc',
    description: 'Steam pressing restoring smooth texture to plain skirts.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Skirt - Long (Steam Iron)',
    category: 'Garments',
    price: 99,
    unit: 'Pc',
    description: 'Pleat-by-pleat steam finishing for long and designer skirts.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Sweater / Sweatshirt (Dry Clean)',
    category: 'Garments',
    price: 199,
    unit: 'Pc',
    description: 'Knitwear specialized wash with anti-pilling treatment and soft cashmere conditioning.',
    turnaroundTime: '24-48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Sweater / Sweatshirt (Steam Iron)',
    category: 'Garments',
    price: 49,
    unit: 'Pc',
    description: 'Gentle touch steam restoration for hoodies, sweaters, and fleece pullovers.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Suit 2-Piece (Coat + Pant) (Dry Clean)',
    category: 'Garments',
    price: 299,
    unit: 'Set',
    description: 'Two-piece formal business suit cleaning, lapel press, and trouser crease alignment.',
    turnaroundTime: '48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Suit 3-Piece (Coat + Waistcoat + Pant) (Dry Clean)',
    category: 'Garments',
    price: 399,
    unit: 'Set',
    description: 'Executive 3-piece suit care including waistcoat conditioning and steam press.',
    turnaroundTime: '48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Suit 2-Piece (Steam Iron)',
    category: 'Garments',
    price: 199,
    unit: 'Set',
    description: 'Full 2-piece corporate suit steam pressing with sharp razor creases.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Suit 3-Piece (Steam Iron)',
    category: 'Garments',
    price: 249,
    unit: 'Set',
    description: 'Complete 3-piece formal steam pressing for coat, vest, and trousers.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Women 2-Piece Kurti Set (Dry Clean)',
    category: 'Garments',
    price: 249,
    unit: 'Set',
    description: 'Matching kurti and pant/palazzo dry cleaning with color-brightening rinse.',
    turnaroundTime: '24-48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Women 2-Piece Kurti Set (Steam Iron)',
    category: 'Garments',
    price: 99,
    unit: 'Set',
    description: 'Steam press for 2-piece kurti and bottom ethnic coordinate sets.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },

  // ==========================================
  // 2. HOME CARE
  // ==========================================
  {
    name: 'Blinds per panel (Dry Clean)',
    category: 'Home Care',
    price: 199,
    unit: 'Panel',
    description: 'Fabric blind cleaning with dust mite extraction and slat-safe gentle drying.',
    turnaroundTime: '48-72 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Curtains per panel - Plain (Dry Clean)',
    category: 'Home Care',
    price: 149,
    unit: 'Panel',
    description: 'Dust and allergen extraction for cotton and linen window curtains.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Curtains per panel - Plain Heavy (Dry Clean)',
    category: 'Home Care',
    price: 249,
    unit: 'Panel',
    description: 'Deep hydro-cleaning for heavy drapes, velvet, and lined room-darkening panels.',
    turnaroundTime: '48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Curtains per panel - Premium / Blackout (Dry Clean)',
    category: 'Home Care',
    price: 249,
    unit: 'Panel',
    description: 'Thermal blackout and designer curtain cleaning safeguarding delicate backing layers.',
    turnaroundTime: '48-72 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Curtains per panel - Plain (Steam Iron)',
    category: 'Home Care',
    price: 99,
    unit: 'Panel',
    description: 'Vertical heavy steam press smoothing out all hang creases.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Curtains per panel - Heavy (Steam Iron)',
    category: 'Home Care',
    price: 149,
    unit: 'Panel',
    description: 'High-steam pleat realignment for heavy velvet and blackout curtain panels.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'BedSheet - Single (Dry Clean)',
    category: 'Home Care',
    price: 149,
    unit: 'Pc',
    description: 'Sanitized hot-water wash and tumble drying with allergen removal for single bedsheets.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'BedSheet - Double (Dry Clean)',
    category: 'Home Care',
    price: 199,
    unit: 'Pc',
    description: 'Deep sanitized cleaning for king and queen double bedsheets with crisp hospital-grade fold.',
    turnaroundTime: '24-48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'BedSheet - Single (Steam Iron)',
    category: 'Home Care',
    price: 49,
    unit: 'Pc',
    description: 'Rotary cylinder steam pressing for smooth single bedsheets.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'BedSheet - Double (Steam Iron)',
    category: 'Home Care',
    price: 99,
    unit: 'Pc',
    description: 'Hotel-finish wide flatwork steam ironing for double king/queen bedsheets.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Dohar (Dry Clean)',
    category: 'Home Care',
    price: 199,
    unit: 'Pc',
    description: 'Gentle summer cotton dohar cleaning with freshness infusion and compact fold.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Blanket - Single (Dry Clean)',
    category: 'Home Care',
    price: 249,
    unit: 'Pc',
    description: 'Deep thermal cleaning for single fleece and mink blankets with fluff rejuvenation.',
    turnaroundTime: '48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Blanket - Double (Dry Clean)',
    category: 'Home Care',
    price: 349,
    unit: 'Pc',
    description: 'Heavy double-ply mink blanket sanitization, odor neutralization, and lint extraction.',
    turnaroundTime: '48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Quilt / Razai - Single (Dry Clean)',
    category: 'Home Care',
    price: 349,
    unit: 'Pc',
    description: 'Cotton and microfiber filled single quilt deep wash with inner batting alignment.',
    turnaroundTime: '48-72 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Quilt / Razai - Double (Dry Clean)',
    category: 'Home Care',
    price: 499,
    unit: 'Pc',
    description: 'Heavy double winter razai and down comforter cleaning with allergen removal and UV drying.',
    turnaroundTime: '48-72 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Pillow (Dry Clean)',
    category: 'Home Care',
    price: 99,
    unit: 'Pc',
    description: 'Dust mite extraction and fluff revitalization for sleeping pillows.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Cushion (Dry Clean)',
    category: 'Home Care',
    price: 149,
    unit: 'Pc',
    description: 'Thorough core cleaning and sanitization for sofa and decorative cushions.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Pillow Cover (Dry Clean)',
    category: 'Home Care',
    price: 39,
    unit: 'Pc',
    description: 'Sanitized cleaning for pillow covers removing hair oil and sweat residues.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Pillow Cover (Steam Iron)',
    category: 'Home Care',
    price: 19,
    unit: 'Pc',
    description: 'Quick crisp steam press for cotton and satin pillow covers.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Cushion Cover (Dry Clean)',
    category: 'Home Care',
    price: 49,
    unit: 'Pc',
    description: 'Gentle cleaning for embroidered, velvet, and brocade decorative cushion covers.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Cushion Cover (Steam Iron)',
    category: 'Home Care',
    price: 29,
    unit: 'Pc',
    description: 'Precision steam pressing for decorative sofa cushion slips.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Table Cover - Plain / Small (Dry Clean)',
    category: 'Home Care',
    price: 199,
    unit: 'Pc',
    description: 'Food stain removal and fabric brightening for 4-seater and coffee table covers.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Table Cover - Large / Embroidered (Dry Clean)',
    category: 'Home Care',
    price: 299,
    unit: 'Pc',
    description: 'Careful dry clean for 6 to 8-seater dining table covers and lace runners.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Dhurrie / Rug (Deep Clean)',
    category: 'Home Care',
    price: 399,
    unit: 'Pc',
    description: 'Traditional cotton dhurrie and floor rug deep scrubbing, rinsing, and moisture extraction.',
    turnaroundTime: '48-72 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Carpet Deep Cleaning (Per Sq. Ft.)',
    category: 'Home Care',
    price: 35,
    unit: 'Sq.ft',
    description: 'Commercial rotary injection-extraction carpet shampooing with antimicrobial odor removal.',
    turnaroundTime: '48-72 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },

  // ==========================================
  // 3. SHOE CARE
  // ==========================================
  {
    name: 'Sports Shoes Basic (Cleaning)',
    category: 'Shoe Care',
    price: 299,
    unit: 'Pair',
    description: 'Mesh & canvas exterior scrub, insole deodorization, and upper stain lifting for running shoes.',
    turnaroundTime: '24-48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Sports Shoes Premium (Cleaning)',
    category: 'Shoe Care',
    price: 599,
    unit: 'Pair',
    description: 'Detailed multi-layer cleaning for Nike, Adidas, Jordan sneakers including knit conditioning and aglet care.',
    turnaroundTime: '48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Leather Shoes (Deep Clean & Polish)',
    category: 'Shoe Care',
    price: 599,
    unit: 'Pair',
    description: 'Wax cream nourishment, leather conditioner, scuff buffing, and mirror gloss finish for formal oxfords & loafers.',
    turnaroundTime: '48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Suede / Nubuck Shoes (Cleaning)',
    category: 'Shoe Care',
    price: 699,
    unit: 'Pair',
    description: 'Zero-water brass brush nap rejuvenation, specialized suede eraser, and hydrophobic stain barrier spray.',
    turnaroundTime: '48-72 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Canvas Shoes (Cleaning)',
    category: 'Shoe Care',
    price: 299,
    unit: 'Pair',
    description: 'Deep soak and stain cleaning for Converse, Vans, and casual canvas footwear.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Shoe White Sole Deep Cleaning',
    category: 'Shoe Care',
    price: 199,
    unit: 'Pair',
    description: 'Oxidation reversal and yellowing removal to restore bright white midsoles.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Shoe Deodorizing & Sanitization',
    category: 'Shoe Care',
    price: 99,
    unit: 'Pair',
    description: 'Medical-grade ozone UV sterilization destroying 99.9% of bacteria and lingering foot odors.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Shoe Dry Cleaning (Comprehensive)',
    category: 'Shoe Care',
    price: 499,
    unit: 'Pair',
    description: 'Complete 360-degree dry cleaning covering upper, tongue, inside lining, laces, and sole.',
    turnaroundTime: '48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },

  // ==========================================
  // 4. BAG CARE
  // ==========================================
  {
    name: 'Backpack (Deep Cleaning)',
    category: 'Bag Care',
    price: 399,
    unit: 'Pc',
    description: 'Heavy dirt extraction from canvas/nylon backpacks, strap degreasing, and zipper care.',
    turnaroundTime: '48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Handbag - Small (Cleaning)',
    category: 'Bag Care',
    price: 399,
    unit: 'Pc',
    description: 'Exterior and interior pocket vacuuming, stain lifting, and metal hardware polishing.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Handbag - Large (Cleaning)',
    category: 'Bag Care',
    price: 699,
    unit: 'Pc',
    description: 'Luxury tote and designer bag deep clean with edge coating and lining sanitization.',
    turnaroundTime: '48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Sling Bag (Cleaning)',
    category: 'Bag Care',
    price: 299,
    unit: 'Pc',
    description: 'Fabric freshening and gentle surface sanitization for compact cross-body bags.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Laptop Bag (Cleaning)',
    category: 'Bag Care',
    price: 399,
    unit: 'Pc',
    description: 'Padded sleeve dust extraction, handle grime treatment, and exterior deep clean.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Travel Bag - Small (Cleaning)',
    category: 'Bag Care',
    price: 499,
    unit: 'Pc',
    description: 'Overnight duffle bag cleaning with antibacterial deodorizing and moisture seal.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Travel Bag - Large (Cleaning)',
    category: 'Bag Care',
    price: 699,
    unit: 'Pc',
    description: 'Heavy duty weekender & gym travel bag deep cleaning and odor removal.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Trolley Bag (Deep Sanitization)',
    category: 'Bag Care',
    price: 799,
    unit: 'Pc',
    description: 'Exterior shell scuff buffing, inner mesh shampoo, handle sanitization, and wheel tune-up.',
    turnaroundTime: '48-72 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },

  // ==========================================
  // 5. OTHERS
  // ==========================================
  {
    name: 'Shoes - Sports (Cleaning - Others)',
    category: 'Others',
    price: 299,
    unit: 'Pair',
    description: 'Everyday athletic sneaker washing and moisture drying.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Shoes - Leather (Cleaning - Others)',
    category: 'Others',
    price: 599,
    unit: 'Pair',
    description: 'Full leather deep hydration, cream polish, and edge coloring.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Slippers (Cleaning)',
    category: 'Others',
    price: 299,
    unit: 'Pair',
    description: 'Sanitized scrub and deodorizing for slides, clogs, and home slippers.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Sandals (Cleaning)',
    category: 'Others',
    price: 499,
    unit: 'Pair',
    description: 'Strap cleaning, footbed stain removal, and sole sanitization for ethnic and casual sandals.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Soft Toy - Small (Sanitization)',
    category: 'Others',
    price: 249,
    unit: 'Pc',
    description: 'Baby-safe organic gentle clean and allergen extraction for toys up to 12 inches.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Soft Toy - Medium (Sanitization)',
    category: 'Others',
    price: 349,
    unit: 'Pc',
    description: 'Fluff restoring and deep antimicrobial sanitization for plush toys (12-24 inches).',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Soft Toy - Large (Sanitization)',
    category: 'Others',
    price: 799,
    unit: 'Pc',
    description: 'Oversized giant teddy bear and jumbo plush cleaning with thermal bacteria sterilization.',
    turnaroundTime: '48-72 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Handbag - Leather (Cleaning - Others)',
    category: 'Others',
    price: 399,
    unit: 'Pc',
    description: 'Supple leather conditioning, gentle surface wipe, and moisture-guard finish.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Purse (Cleaning)',
    category: 'Others',
    price: 399,
    unit: 'Pc',
    description: 'Wallet and clutch pocket deep clean with snap closure lubrication.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Bag / Travel Bag - Small',
    category: 'Others',
    price: 499,
    unit: 'Pc',
    description: 'Compact travel and overnight bag sanitization with fresh scent treatment.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Bag / Travel Bag - Medium',
    category: 'Others',
    price: 699,
    unit: 'Pc',
    description: 'Mid-sized duffle and travel bag deep cleaning.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Bag / Travel Bag - Large',
    category: 'Others',
    price: 999,
    unit: 'Pc',
    description: 'Heavy-duty oversized travel gear cleaning and fabric protection.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Suit Case - Small (Cleaning)',
    category: 'Others',
    price: 399,
    unit: 'Pc',
    description: 'Cabin size hard/soft suitcase sanitization and surface restoration.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Suit Case - Medium (Cleaning)',
    category: 'Others',
    price: 599,
    unit: 'Pc',
    description: 'Medium check-in luggage deep vacuuming and exterior scuff removal.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Suit Case - Large (Cleaning)',
    category: 'Others',
    price: 999,
    unit: 'Pc',
    description: 'Full-size 28-32 inch international luggage deep sanitization, odor neutralizer, and wheel lubricate.',
    turnaroundTime: '48-72 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },

  // ==========================================
  // 6. LAUNDRY
  // ==========================================
  {
    name: 'Wash & Fold (Per Kg)',
    category: 'Laundry',
    price: 99,
    unit: 'Kg',
    description: 'Premium everyday laundry washed in RO soft water with German eco-detergents, tumble dried, and neatly bundled.',
    turnaroundTime: '24-48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1545173168-9f1947eebb7f?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Wash & Iron (Per Kg)',
    category: 'Laundry',
    price: 119,
    unit: 'Kg',
    description: 'Complete laundry care: Soft-water wash, low-heat drying, and crisp vacuum steam ironing per kilogram.',
    turnaroundTime: '24-48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Premium Laundry (Per Kg)',
    category: 'Laundry',
    price: 149,
    unit: 'Kg',
    description: 'Exclusive garment wash with enzyme stain soak, fabric softener, optical brightening, and hanger delivery.',
    turnaroundTime: '24-48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Express Laundry (Per Kg)',
    category: 'Laundry',
    price: 179,
    unit: 'Kg',
    description: 'Fast-track priority laundry with rapid turnaround within 12 to 24 hours delivered to your doorstep.',
    turnaroundTime: '12-24 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1545173168-9f1947eebb7f?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Steam Iron (Per Pc)',
    category: 'Laundry',
    price: 29,
    unit: 'Pc',
    description: 'Individual per-piece vacuum steam pressing for daily wear shirts, tops, trousers, and cottons.',
    turnaroundTime: '12-24 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
];

module.exports = { DEFAULT_SERVICES };
