/**
 * Wash & Wow - Comprehensive Services Catalog
 * 10 premium services per category across all 6 categories (Total: 60 products)
 * Shop: WASH & WOW, Soron Gate Main Market Rd, Jakharudder Pur, Kasganj, UP 207123
 * Phone: +91 90585 54448
 */

const DEFAULT_SERVICES = [
  // ==========================================
  // 1. DRY CLEANING (10 Products)
  // ==========================================
  {
    name: "Men's 2-Piece Suit (Coat + Pant)",
    category: 'Dry Cleaning',
    price: 350,
    unit: 'Set',
    description: 'Executive dry cleaning with closed-loop hydrocarbon solvent, stain removal, and micro-suction steam pressing for coat and trousers.',
    turnaroundTime: '48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: "Men's 3-Piece Suit (Coat + Waistcoat + Pant)",
    category: 'Dry Cleaning',
    price: 450,
    unit: 'Set',
    description: 'Complete three-piece formal suit dry cleaning with specialized lapel shaping, waistcoat rejuvenation, and sharp crease press.',
    turnaroundTime: '48-72 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Blazer / Sports Coat',
    category: 'Dry Cleaning',
    price: 220,
    unit: 'Piece',
    description: 'Premium blazer dry cleaning with inner lining disinfection, shoulder pad contour retention, and zero-shine steam finish.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1593032465175-481ac7f401a0?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Executive Formal Shirt',
    category: 'Dry Cleaning',
    price: 90,
    unit: 'Piece',
    description: 'Delicate chemical wash for formal shirts, cuff and collar grime removal, followed by German tension steam pressing.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Formal Trousers / Chinos',
    category: 'Dry Cleaning',
    price: 110,
    unit: 'Piece',
    description: 'Gentle dry cleaning for trousers, food/oil stain spotting, fiber softening, and long-lasting knife-edge crease alignment.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Puffer Jacket / Winter Bomber',
    category: 'Dry Cleaning',
    price: 280,
    unit: 'Piece',
    description: 'Specialized down-feather and polyfill safe wash that restores puffiness, repels water stains, and deodorizes thoroughly.',
    turnaroundTime: '48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Heavy Trench Coat / Overcoat',
    category: 'Dry Cleaning',
    price: 380,
    unit: 'Piece',
    description: 'Full-length overcoat dry cleaning with moth-proofing, deep dust-trap cleaning, and structured mannequin steaming.',
    turnaroundTime: '48-72 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1539533018447-63fcce667883?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Woolen Sweater / Pullover',
    category: 'Dry Cleaning',
    price: 140,
    unit: 'Piece',
    description: 'Zero-shrinkage conditioning for pure wool, angora, and cashmere knitwear. Prevents pilling and restores soft touch.',
    turnaroundTime: '48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Ethnic Kurta Pajama (Men)',
    category: 'Dry Cleaning',
    price: 190,
    unit: 'Set',
    description: 'Dry cleaning for traditional cotton, raw silk, and linen kurta pajamas with crisp starch balancing and steam finish.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Ladies Designer Top / Blouse',
    category: 'Dry Cleaning',
    price: 120,
    unit: 'Piece',
    description: 'Gentle solvent care for chiffon, crepe, organza, and embroidered blouses with lace and button protection.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },

  // ==========================================
  // 2. WASH & FOLD (10 Products)
  // ==========================================
  {
    name: 'Daily Wash & Fold (By Weight / KG)',
    category: 'Wash & Fold',
    price: 89,
    unit: 'Kg',
    description: 'Everyday laundry washed with bio-detergents and fabric softener, tumble dried, and neatly machine-folded by kilogram.',
    turnaroundTime: '24-48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Casual Shirt (Wash & Fold)',
    category: 'Wash & Fold',
    price: 50,
    unit: 'Piece',
    description: 'Sanitized water wash with collar scrubbing, gentle fabric conditioning, and crisp square fold ready for the wardrobe.',
    turnaroundTime: '24 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'T-Shirt / Polo (Wash & Fold)',
    category: 'Wash & Fold',
    price: 45,
    unit: 'Piece',
    description: 'Color-protecting enzyme wash for round neck and polo tees with zero collar twisting or color fade.',
    turnaroundTime: '24 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Jeans / Denim Trousers (Wash & Fold)',
    category: 'Wash & Fold',
    price: 65,
    unit: 'Piece',
    description: 'Deep denim cleansing that protects indigo pigments, cleans heavy soil from cuffs, and delivers clean tumble-dried jeans.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1542272604-780c96856592?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Casual Trousers / Chinos (Wash & Fold)',
    category: 'Wash & Fold',
    price: 60,
    unit: 'Piece',
    description: 'Gentle wash cycle with anti-wrinkle conditioning and neat fold for chinos, khakis, and cargo pants.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Cotton Kurti (Wash & Fold)',
    category: 'Wash & Fold',
    price: 55,
    unit: 'Piece',
    description: 'Daily wear cotton and rayon kurtis washed with mild conditioning agents to retain bright colors and soft texture.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Shorts / Track Pants / Bermudas',
    category: 'Wash & Fold',
    price: 45,
    unit: 'Piece',
    description: 'Fresh hygiene wash for gym tracks, running shorts, and sleep bermudas with antimicrobial rinse.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Bath Towel / Hand Towel (Wash & Fold)',
    category: 'Wash & Fold',
    price: 40,
    unit: 'Piece',
    description: 'Thermal disinfection wash for plush cotton towels followed by warm air tumble drying for ultimate fluffiness.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1616627547584-bf28cee262db?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Gym & Sports Activewear',
    category: 'Wash & Fold',
    price: 50,
    unit: 'Piece',
    description: 'Sweat odor eliminator wash designed specifically for spandex, polyester, and Dri-FIT workout apparel.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Nightwear / Pajama Set (Wash & Fold)',
    category: 'Wash & Fold',
    price: 70,
    unit: 'Set',
    description: 'Complete sleep set wash with calming lavender fabric softening and wrinkle-free fold.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },

  // ==========================================
  // 3. STEAM IRON (10 Products)
  // ==========================================
  {
    name: 'Shirt Steam Press',
    category: 'Steam Iron',
    price: 15,
    unit: 'Piece',
    description: 'High-temperature steam pressing with crisp collar, cuff, and placket perfection without scorching or shine marks.',
    turnaroundTime: '12-24 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Pant / Trouser Steam Press',
    category: 'Steam Iron',
    price: 18,
    unit: 'Piece',
    description: 'Dual-vacuum industrial table pressing that delivers razor-sharp front and back leg crease alignment.',
    turnaroundTime: '12-24 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Jeans / Denim Steam Press',
    category: 'Steam Iron',
    price: 20,
    unit: 'Piece',
    description: 'Heavy steam penetration for thick denim fabric, smoothing pockets, seams, and waistband.',
    turnaroundTime: '12-24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1542272604-780c96856592?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'T-Shirt / Polo Steam Press',
    category: 'Steam Iron',
    price: 15,
    unit: 'Piece',
    description: 'Gentle temperature steam gliding to remove all wrinkles and creases without stretching necklines.',
    turnaroundTime: '12-24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Ethnic Kurta Steam Press',
    category: 'Steam Iron',
    price: 25,
    unit: 'Piece',
    description: 'Extended flatbed steam alignment for cotton, silk, and linen kurtas, preserving embroidery and buttons.',
    turnaroundTime: '12-24 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Saree Steam Press (Standard)',
    category: 'Steam Iron',
    price: 60,
    unit: 'Piece',
    description: 'Uniform roller steam pressing that flattens wrinkles across 6 yards of fabric without damaging pallu or borders.',
    turnaroundTime: '24 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Suit / Blazer Steam Press',
    category: 'Steam Iron',
    price: 100,
    unit: 'Piece',
    description: 'Form-finishing steam mannequin press that restores 3D shoulder shape, chest drape, and lapel curvature.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Ladies Salwar Suit Steam Press',
    category: 'Steam Iron',
    price: 40,
    unit: 'Set',
    description: 'Complete 3-piece pressing for kameez, bottom/salwar, and dupatta with wrinkle-free packaging.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Bedsheet Steam Press (Single/Double)',
    category: 'Steam Iron',
    price: 50,
    unit: 'Piece',
    description: 'Industrial flatwork ironer pressing that delivers crisp five-star hotel quality finish to bed linens.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Curtain Steam Press (Per Panel)',
    category: 'Steam Iron',
    price: 70,
    unit: 'Piece',
    description: 'Vertical heavy steam finish to remove packing wrinkles and crease folds on home curtains.',
    turnaroundTime: '24 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },

  // ==========================================
  // 4. PREMIUM CARE (10 Products)
  // ==========================================
  {
    name: 'Pure Silk Saree Dry Clean',
    category: 'Premium Care',
    price: 250,
    unit: 'Piece',
    description: 'Bespoke hand dry-cleaning for Banarasi, Kanjeevaram, and Tussar silks using zero-water Italian hydrocarbon solvents.',
    turnaroundTime: '48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Heavy Zari / Embroidered Saree',
    category: 'Premium Care',
    price: 350,
    unit: 'Piece',
    description: 'Ultrasonic spot lifting and mesh net wrapping for heavy golden zari, beadwork, and cutdana embroidery.',
    turnaroundTime: '48-72 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Bridal Wedding Lehenga Set',
    category: 'Premium Care',
    price: 750,
    unit: 'Set',
    description: 'Royal bridal couture cleaning for lehenga skirt, embellished choli, and dual dupattas with acid-free tissue wrapping.',
    turnaroundTime: '72 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Designer Groom Sherwani Set',
    category: 'Premium Care',
    price: 550,
    unit: 'Set',
    description: 'Specialist dry clean for raw silk, jacquard, and velvet sherwanis with jeweled button preservation and churidar press.',
    turnaroundTime: '72 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Pashmina & Cashmere Shawl Care',
    category: 'Premium Care',
    price: 220,
    unit: 'Piece',
    description: 'Ultra-gentle temperature-controlled conditioning that protects fragile goat hair fibers and natural cashmere softness.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Genuine Leather Jacket Restoration',
    category: 'Premium Care',
    price: 650,
    unit: 'Piece',
    description: 'Deep surface dirt removal, leather hydration balm treatment, color enhancement, and water-repellent seal.',
    turnaroundTime: '4-5 Days',
    popular: false,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Evening Gown / Anarkali Dress',
    category: 'Premium Care',
    price: 390,
    unit: 'Piece',
    description: 'Multi-layer flare care for satin, net, and velvet ball gowns with delicate hand spotting and hemline stain extraction.',
    turnaroundTime: '48-72 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Tuxedo (With Silk/Satin Lapels)',
    category: 'Premium Care',
    price: 480,
    unit: 'Set',
    description: 'Black-tie tuxedo chemical dry clean with specialized sheen protection on satin lapels and trousers braid.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Saree Roll Polish & Charak',
    category: 'Premium Care',
    price: 180,
    unit: 'Piece',
    description: 'Traditional heated roller calendering polish that restores natural silk shine and smooth fall without chemical damage.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Heavy Embellished Dupatta / Chunni',
    category: 'Premium Care',
    price: 130,
    unit: 'Piece',
    description: 'Hand cleaning for net, organza, and velvet dupattas with gota-patti and sequin work.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },

  // ==========================================
  // 5. HOUSEHOLD (10 Products)
  // ==========================================
  {
    name: 'Double Blanket / Quilt / Razai',
    category: 'Household',
    price: 300,
    unit: 'Piece',
    description: 'Anti-bacterial steam cleaning, dust mite extermination, and high-volume warm air fluff drying for king/queen blankets.',
    turnaroundTime: '48-72 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Single Blanket / Comforter',
    category: 'Household',
    price: 200,
    unit: 'Piece',
    description: 'Deep fiber sanitization, stain spot removal, and fragrant tumble drying for single beds and winter dohars.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Double Bedsheet Set (With 2 Pillows)',
    category: 'Household',
    price: 120,
    unit: 'Set',
    description: 'Deep bio-wash to remove body oils and sweat, fabric brightening treatment, and crisp flatwork iron pressing.',
    turnaroundTime: '24-48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Single Bedsheet (With 1 Pillow)',
    category: 'Household',
    price: 80,
    unit: 'Set',
    description: 'Hygienic disinfectant wash with hot water rinse and smooth flatbed pressing.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Window Curtains (Per Panel)',
    category: 'Household',
    price: 100,
    unit: 'Piece',
    description: 'High-suction dust extraction followed by gentle solvent wash and anti-static vertical steam pressing per panel.',
    turnaroundTime: '48-72 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Door & Blackout Curtains (Per Panel)',
    category: 'Household',
    price: 150,
    unit: 'Piece',
    description: 'Heavy thermal drape cleaning that lifts environmental pollutants without peeling light-blocking rubber backing.',
    turnaroundTime: '48-72 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Carpet & Rug Deep Cleaning (Per Sq. Ft.)',
    category: 'Household',
    price: 35,
    unit: 'Sq Ft',
    description: 'Industrial rotary shampooing, active stain lifting, hot water extraction, and rapid moisture-free drying.',
    turnaroundTime: '3-4 Days',
    popular: false,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Sofa / Cushion Cover (Set of 5)',
    category: 'Household',
    price: 150,
    unit: 'Set',
    description: 'Fabric-safe stain removal for living room sofa cushion covers with anti-allergen treatment.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Mattress Protector / Topper',
    category: 'Household',
    price: 220,
    unit: 'Piece',
    description: 'Waterproof membrane safe sanitization, anti-dust-mite treatment, and deodorizing rinse.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Bed Pillow / Cushion (Wash & Fluff)',
    category: 'Household',
    price: 90,
    unit: 'Piece',
    description: 'Pillow core wash, sweat stain extraction, and ultra-fluff air drying with soothing fragrance.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },

  // ==========================================
  // 6. FOOTWEAR (10 Products)
  // ==========================================
  {
    name: 'Sneakers Deep Clean & Deodorize',
    category: 'Footwear',
    price: 200,
    unit: 'Pair',
    description: 'Detailed hand scrub, midsole brightening, lace wash, insole sterilization, and anti-fungal UV deodorizing treatment.',
    turnaroundTime: '48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Formal Leather Shoes Spa & Polish',
    category: 'Footwear',
    price: 250,
    unit: 'Pair',
    description: 'Gentle leather wax cleansing, crease reduction, natural essential oil nourishment, and hand buffed mirror-shine polish.',
    turnaroundTime: '48 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Suede & Nubuck Shoe Restoration',
    category: 'Footwear',
    price: 300,
    unit: 'Pair',
    description: 'Specialist brass-bristle suede nap rejuvenation, liquid stain eraser, color revival spray, and nano water-barrier coat.',
    turnaroundTime: '48-72 Hours',
    popular: true,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Sports & Running Shoes Cleaning',
    category: 'Footwear',
    price: 180,
    unit: 'Pair',
    description: 'Breathable mesh stain extraction, odor-neutralizing insole rinse, and high-traction sole dirt removal.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Canvas Shoes (Converse / Vans) Wash',
    category: 'Footwear',
    price: 160,
    unit: 'Pair',
    description: 'Deep soil scrub for canvas uppers, white rubber sidewall restoration, and brand-new lace brightening.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Winter Boots / High Tops Care',
    category: 'Footwear',
    price: 290,
    unit: 'Pair',
    description: 'Heavy mud and salt extraction, ankle collar sanitization, and moisture-resistant conditioning for tall boots.',
    turnaroundTime: '48-72 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Casual Loafers & Slip-Ons',
    category: 'Footwear',
    price: 200,
    unit: 'Pair',
    description: 'Insole disinfectant rinse, outer fabric stain lifting, and moisture-shield protective spray.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Ladies Heels & Party Stilettos',
    category: 'Footwear',
    price: 220,
    unit: 'Pair',
    description: 'Delicate care for satin, patent, and glitter party heels with sole grime removal and heel-tip protection.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Ethnic Mojaris / Juttis Cleaning',
    category: 'Footwear',
    price: 190,
    unit: 'Pair',
    description: 'Embroidery and zari thread protection, hand foam cleaning, and leather sole softening for traditional wedding juttis.',
    turnaroundTime: '48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    name: 'Sole Un-Yellowing & Scuff Eraser',
    category: 'Footwear',
    price: 150,
    unit: 'Pair',
    description: 'Special chemical de-oxidation therapy that turns yellowed rubber soles back to icy white.',
    turnaroundTime: '24-48 Hours',
    popular: false,
    image: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600&auto=format&fit=crop&q=80',
    isActive: true,
  },
];

module.exports = { DEFAULT_SERVICES };
